# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0010_auto_20170120_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='owned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='rip',
            field=models.BooleanField(default=False),
        ),
    ]
