# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-27 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0011_auto_20171127_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
