# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0012_album_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='wanted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.CharField(choices=[('loveit', 'Love it'), ('mixitup', 'Not my thing, but nice to mix it up'), ('nothanks', 'Good, but OK if I never hear it again'), ('notgood', 'Not good'), ('undecided', 'Undecided'), ('unrated', 'Unrated')], default='unrated', max_length=20),
        ),
        migrations.AlterField(
            model_name='album',
            name='tracks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='albumstatus',
            name='status',
            field=models.CharField(choices=[('incomplete', 'The album is incomplete'), ('mislabeled', 'The album is mislabeled'), ('rip', 'The album has ripping problems'), ('owned', 'The album exists materially'), ('follow', 'The artist is of particular interest')], max_length=20),
        ),
    ]
