# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0013_auto_20180206_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumstatus',
            name='status',
            field=models.CharField(choices=[('incomplete', 'The album is incomplete'), ('mislabeled', 'The album is mislabeled'), ('rip', 'The album has ripping problems'), ('owned', 'The album exists materially'), ('wanted', 'This album is sought after'), ('follow', 'The artist is of particular interest')], max_length=20),
        ),
    ]
