# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-02 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0016_auto_20190707_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistsong',
            name='queue_number',
            field=models.IntegerField(default=1),
        ),
    ]
