# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-09 22:00
from __future__ import unicode_literals

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    PlaylistSong = apps.get_model("beater", "PlaylistSong")
    for playlistsong in PlaylistSong.objects.all():
        playlistsong.play_count = 1 if playlistsong.played else 0
        playlistsong.save()

def reverse_func(apps, schema_editor):
    PlaylistSong = apps.get_model("beater", "PlaylistSong")
    for playlistsong in PlaylistSong.objects.all():
        playlistsong.played = 1 if playlistsong.play_count > 0 else 0
        playlistsong.save()

class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0017_playlistsong_queue_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistsong',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.RemoveField(
            model_name='playlistsong',
            name='played'
        )
    ]
