# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-10 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0018_playlistsong_play_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='musicbrainz_trackid',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='tracknumber',
            field=models.IntegerField(null=True),
        ),
    ]
