# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-10 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0019_auto_20200210_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='musicbrainz_albumid',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='musicbrainz_trmid',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='organization',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='musicbrainz_artistid',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
