# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-11 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0020_auto_20200210_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mute_state', models.BooleanField(default=False)),
                ('shuffle_state', models.BooleanField(default=False)),
                ('playlist_mode', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='on', max_length=3)),
                ('state', models.CharField(choices=[('stopped', 'Stopped'), ('playing', 'Playing'), ('paused', 'Paused')], default='stopped', max_length=7)),
                ('cursor_mode', models.CharField(choices=[('next', 'Next'), ('static', 'Static')], default='next', max_length=6)),
            ],
        ),
    ]
