# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-16 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0021_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='mute_state',
            new_name='mute',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='shuffle_state',
            new_name='shuffle',
        ),
    ]
