# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-18 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0022_auto_20200216_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistsong',
            name='last_played_at',
            field=models.DateTimeField(null=True),
        ),
    ]
