# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-18 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0024_remove_player_playlist_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='beatplayer_status',
            field=models.CharField(choices=[('down', 'Down'), ('up', 'Up')], default='down', max_length=4),
        ),
    ]
