# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-22 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0025_player_beatplayer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='beatplayer_status',
        ),
    ]
