# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-07 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0029_auto_20200307_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='beatplayer_volume',
            new_name='volume',
        ),
    ]
