# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-14 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0030_auto_20200307_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='last_played_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
    ]
