# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-30 16:42
from __future__ import unicode_literals

import beater.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0031_auto_20200314_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeatPlayerClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beatplayer_url', models.CharField(max_length=255)),
                ('freshbeats_callback_url', models.CharField(max_length=255)),
                ('last_report_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('notready', 'Not Ready'), ('down', 'Down')], default='down', max_length=20)),
                ('reachable', models.BooleanField(default=False)),
                ('registered', models.BooleanField(default=False)),
                ('mounted', models.BooleanField(default=False)),
                ('selfreport', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(default=beater.models.get_created_at),
        ),
    ]
