# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-30 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0032_auto_20201030_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatplayerclient',
            name='last_report_at',
            field=models.DateTimeField(null=True),
        ),
    ]
