# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-30 16:50
from __future__ import unicode_literals

import beater.common.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0033_auto_20201030_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(default=beater.common.util.get_localized_now),
        ),
    ]
