# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-10-31 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0034_auto_20201030_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatplayerclient',
            name='registered_at',
            field=models.DateTimeField(null=True),
        ),
    ]
