# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-01 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0035_beatplayerclient_registered_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beatplayerclient',
            old_name='last_report_at',
            new_name='last_health_check',
        ),
    ]
