# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-26 01:01
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    Playlist = apps.get_model("beater", "Playlist")
    default_playlist = Playlist.objects.filter(name='Default').first()
    if default_playlist is None:
        default_playlist = Playlist.objects.create(name='Default')    
    
    PlaylistSong = apps.get_model("beater", "PlaylistSong")
    for playlistsong in PlaylistSong.objects.filter(playlist=None):        
        playlistsong.playlist_id = default_playlist.id 
        playlistsong.save()

def reverse_func(apps, schema_editor):
    pass
    
class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0038_auto_20201126_0059'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
