# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-29 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0041_populate_beatplayerclient_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beatplayerclient',
            name='beatplayer_url',
        ),
        migrations.AddField(
            model_name='player',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beater.Device'),
        ),
    ]
