# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-29 06:43
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0042_auto_20201129_0642'),
    ]

    operations = [
        migrations.RunSQL('update beater_player set device_id = (select id from beater_device where agent_base_url = \'http://127.0.0.1:9000\' limit 1)'),
    ]
