# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-29 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0044_auto_20201129_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beatplayerclient',
            name='device',
        ),
        migrations.DeleteModel(
            name='BeatPlayerClient',
        ),
    ]
