# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-07 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0046_auto_20201201_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_player', to='beater.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_device', to='beater.Device'),
        ),
    ]
