# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-07 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0047_auto_20201207_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='device',
        ),
    ]
