# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-07 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0048_remove_player_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='beater.Player'),
        ),
    ]
