# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-11 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0051_device_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistsong',
            name='is_current',
        ),
    ]
