# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-11 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0052_remove_playlistsong_is_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='active',
            new_name='is_active',
        ),
    ]
