# Generated by Django 2.2.17 on 2021-01-05 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0055_auto_20201231_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='beater.Artist'),
        ),
        migrations.AlterField(
            model_name='player',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='beater.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='playlistsong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='beater.PlaylistSong'),
        ),
        migrations.AlterField(
            model_name='playlistsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beater.Song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beater.Album'),
        ),
    ]
