# Generated by Django 2.2.17 on 2021-01-05 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0056_auto_20210105_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playlistsong',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='beater.PlaylistSong'),
        ),
    ]
