# Generated by Django 2.2.17 on 2021-01-06 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0058_auto_20210105_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playlistsong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beater.PlaylistSong'),
        ),
    ]
