# Generated by Django 2.2.17 on 2021-01-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0059_auto_20210106_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.URLField(max_length=2048, null=True),
        ),
    ]
