# Generated by Django 2.0 on 2021-09-25 09:19

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0060_song_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(null=True)),
                ('last_health_check', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('notready', 'Not Ready'), ('down', 'Down')], default='down', max_length=20)),
                ('reachable', models.BooleanField(default=False)),
                ('registered', models.BooleanField(default=False)),
                ('mounted', models.BooleanField(default=False)),
                ('selfreport', models.BooleanField(default=False)),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='device',
            name='health',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='beater.DeviceHealth'),
        ),
    ]
