# Generated by Django 2.0 on 2021-09-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0061_auto_20210925_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='last_health_check',
        ),
        migrations.RemoveField(
            model_name='device',
            name='mounted',
        ),
        migrations.RemoveField(
            model_name='device',
            name='reachable',
        ),
        migrations.RemoveField(
            model_name='device',
            name='registered',
        ),
        migrations.RemoveField(
            model_name='device',
            name='registered_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='selfreport',
        ),
        migrations.RemoveField(
            model_name='device',
            name='status',
        ),
    ]
