# Generated by Django 2.0 on 2021-09-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0062_auto_20210925_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicehealth',
            name='last_client_presence',
            field=models.DateTimeField(null=True),
        ),
    ]
