# Generated by Django 2.0 on 2021-09-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0063_devicehealth_last_client_presence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicehealth',
            old_name='last_health_check',
            new_name='last_device_health_report',
        ),
    ]
