# Generated by Django 2.0 on 2021-09-27 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0064_auto_20210926_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicehealth',
            name='registered',
        ),
        migrations.RemoveField(
            model_name='devicehealth',
            name='selfreport',
        ),
    ]
