# Generated by Django 2.0.13 on 2022-01-18 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0066_auto_20210927_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='owned',
        ),
        migrations.RemoveField(
            model_name='album',
            name='rip',
        ),
        migrations.RemoveField(
            model_name='album',
            name='wanted',
        ),
    ]
