# Generated by Django 2.0.13 on 2022-02-13 08:58

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0067_auto_20220118_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='albumcheckout',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='beater.Album'),
        ),
        migrations.AddField(
            model_name='albumcheckout',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beater.Mobile', null=True),
            preserve_default=False,
        ),
    ]
