# Generated by Django 2.0.13 on 2022-02-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0068_auto_20220213_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumcheckout',
            name='request_priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='albumcheckout',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('validated', 'Validated'), ('checkedout', 'Checked-out'), ('checkedin', 'Checked-in')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='albumcheckout',
            name='checkout_at',
            field=models.DateTimeField(null=True),
        ),
    ]
