# Generated by Django 2.0.13 on 2022-02-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0070_auto_20220214_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumcheckout',
            name='next_state',
            field=models.CharField(choices=[('requested', 'Requested'), ('validated', 'Validated'), ('checkedout', 'Checked-out'), ('refresh', 'Refresh'), ('tocheckin', 'To check-in'), ('checkedin', 'Checked-in')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='albumcheckout',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('validated', 'Validated'), ('checkedout', 'Checked-out'), ('refresh', 'Refresh'), ('tocheckin', 'To check-in'), ('checkedin', 'Checked-in')], default='requested', max_length=20),
        ),
    ]
