# Generated by Django 2.0.13 on 2022-02-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0071_auto_20220216_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumcheckout',
            name='next_state',
            field=models.CharField(choices=[('checkedout', 'Checked-out'), ('refresh', 'Refresh'), ('checkedin', 'Checked-in')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='albumcheckout',
            name='state',
            field=models.CharField(choices=[('requested', 'Requested'), ('validated', 'Validated'), ('checkedout', 'Checked-out'), ('checkedin', 'Checked-in')], default='requested', max_length=20),
        ),
    ]
