# Generated by Django 2.0.13 on 2022-02-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0072_auto_20220217_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelname', models.CharField(max_length=255, null=True)),
                ('levelnolineno', models.IntegerField(default=1)),
                ('message', models.CharField(max_length=255, null=True)),
                ('asctime', models.DateTimeField()),
                ('processName', models.CharField(max_length=255, null=True)),
                ('funcName', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('linenolineno', models.IntegerField(default=1)),
                ('pathname', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mobile',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='ssh_private_key_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='ssh_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
