# Generated by Django 4.0.6 on 2023-04-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beater', '0074_rename_levelnolineno_log_levelno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
