version: "3"
services:
  freshbeats_app:
    image: ${DOCKER_REGISTRY}freshbeats:latest
    build: 
      context: .
      #args:
      #- gitcommithash=05c10666dcb5829f574881f6ab1b2cbdd05f8ec8
    container_name: freshbeats_app
    env_file: webapp/container.env
    ports:
      - "8030:8000"
    environment:
     - PYTHONUNBUFFERED=1
    restart: "always"
    external_links:
      - frankdb_mysql
    networks:
      - frankenbridge
  freshbeats_switchboard:
    image: ${DOCKER_REGISTRY}switchboard:latest
    build: 
      context: services/switchboard
    container_name: freshbeats_switchboard
    ports:
      - 3333:3333
    restart: "always"
    networks:
      - frankenbridge
  freshbeats_beatplayer:
    image: ${DOCKER_REGISTRY}beatplayer:latest
    build: 
      context: services/beatplayer
      args:
        - ALPINE_ARCH=amd64
    container_name: freshbeats_beatplayer
    ports:
      - 9000:9000
    restart: "always"
    env_file: services/beatplayer/.env
    networks:
      - frankenbridge 
networks:
  frankenbridge:
    external: true
