version: "3.3"
services:
  freshbeats:
    build: .
    ports:
      - "8000:8000"
    environment:
     - PYTHONUNBUFFERED=1
    networks:
      - frankenbridge
networks:
  frankenbridge:
    external: yes
