version: "3.3"
services:
  freshbeats_app:
    image: freshbeats:latest
    build: .
      # context: .
      # args:
      #   - gitcommithash=05c10666dcb5829f574881f6ab1b2cbdd05f8ec8
    container_name: freshbeats_app
    # ports:
    #   - "8030:8000"
    environment:
     - PYTHONUNBUFFERED=1
    env_file:
      - webapp/.env
    restart: "always"
    external_links:
      - frankdb_mysql
    networks:
      - frankenbridge
  freshbeats_switchboard:
    image: switchboard:latest
    build: services/switchboard
    container_name: freshbeats_switchboard
    restart: "always"
    networks:
      - frankenbridge
networks:
  frankenbridge:
    external: yes
