- name: create service folder
  file:
    state: directory
    path: /opt/freshbeats
  become: yes
  become_user: root

- name: install beater service
  synchronize:
    src: "{{ role_path }}/../../../services/beatplayer"
    dest: /opt/freshbeats
    delete: yes
    private_key: "/home/debian/{{ deploy_user }}/.ssh/id_rsa"

- name: install beater service description
  template:
    src: beatplayer.service.j2
    dest: /etc/systemd/system/beatplayer.service
  become: yes
  become_user: root

- name: start beater service
  systemd:
    name: beatplayer
    daemon_reload: yes
    enabled: yes
    state: started
  become: yes
  become_user: root
