version: "3.3"
services:
  freshbeats_switchboard:
    image: ${DOCKER_REGISTRY}switchboard:latest
    build: 
      context: .
    container_name: freshbeats_switchboard
    ports:
      - 3333:3333
    restart: "always"
    networks:
      - frankenbridge
networks:
  frankenbridge:
    external: yes
