version: "3.3"
services:
  beatplayer:
    image: frankendeb:5000/beatplayer:latest
    container_name: freshbeats_beatplayer
    restart: "always"
    volumes:
      - ${HOST_MUSIC_FOLDER}:/mnt/music
    devices:
      - /dev/snd
    ports:
      - 9000:9000
    env_file: .env 
