version: "2.2"
services:
  beatplayer:
    image: ${DOCKER_REGISTRY}beatplayer:${CPU_ARCH}
    build:
      context: .
      args:
        - ALPINE_ARCH
    container_name: freshbeats_beatplayer
    restart: "always"
    volumes:
      - ${BEATPLAYER_HOST_MUSIC_FOLDER}:/mnt/music:ro
      - /tmp:/tmp
    devices:
      - /dev/snd
    ports:
      - ${BEATPLAYER_PORT}:${BEATPLAYER_PORT}
    env_file: .env 
    external_links:
      - freshbeats_app
    networks:
      - frankenbridge
networks:
  frankenbridge:
    external: yes
    