version: "2.0"
services:
  beatplayer:
    image: registry.palkosoftware.net:5000/beatplayer:${ARCH}
    build: .
    container_name: freshbeats_beatplayer
    restart: "always"
    volumes:
      - ${HOST_MUSIC_FOLDER}:/mnt/music
      - /tmp:/tmp
    devices:
      - /dev/snd
    ports:
      - 9000:9000
    env_file: .env 
