version: "2.0"
services:
  beatplayer:
    image: ${DOCKER_REGISTRY}beatplayer:${ARCH}
    container_name: freshbeats_beatplayer
    restart: "always"
    volumes:
      - ${HOST_MUSIC_FOLDER}:/mnt/music:ro
      - /tmp:/tmp
    devices:
      - /dev/snd
    ports:
      - ${BEATPLAYER_PORT}:${BEATPLAYER_PORT}
    env_file: .env 
